# Generated by Django 4.2.28 on 2026-03-03 11:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('specialization', models.CharField(blank=True, default='General Physician', max_length=100)),
                ('hospital', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('pharmacy_name', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('pharmacy', 'Pharmacy')], max_length=20)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be 10 digits, cannot start with 0', regex='^[1-9][0-9]{9}$')])),
                ('ethereum_address', models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Ethereum address. Must be 0x + 40 hex chars', regex='^0x[a-fA-F0-9]{40}$')])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'indexes': [models.Index(fields=['user_type'], name='prescriptio_user_ty_359204_idx'), models.Index(fields=['ethereum_address'], name='prescriptio_ethereu_2df2af_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=64, unique=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('data_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('blockchain_verified', models.BooleanField(default=False)),
                ('doctor_wallet', models.CharField(blank=True, max_length=42, null=True)),
                ('patient_wallet', models.CharField(blank=True, max_length=42, null=True)),
                ('disease', models.CharField(max_length=200)),
                ('drug', models.TextField()),
                ('dosage', models.CharField(blank=True, max_length=200, null=True)),
                ('frequency', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('adverse_effects', models.TextField(blank=True, null=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='prescriptions.doctor')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='prescriptions.pharmacy')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='prescriptions.patient')),
            ],
            options={
                'verbose_name': 'Prescription Record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prescription_id'], name='prescriptio_prescri_3c2322_idx'), models.Index(fields=['transaction_hash'], name='prescriptio_transac_9d0b3c_idx'), models.Index(fields=['created_at'], name='prescriptio_created_9b6065_idx'), models.Index(fields=['is_filled'], name='prescriptio_is_fill_4be700_idx'), models.Index(fields=['is_cancelled'], name='prescriptio_is_canc_a1c85a_idx')],
            },
        ),
    ]
