# Generated by Django 4.2.28 on 2026-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.RemoveIndex(
            model_name='prescriptionrecord',
            name='prescriptio_transac_9d0b3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescriptionrecord',
            name='prescriptio_created_9b6065_idx',
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_licenses/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='pharmacy_licenses/'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
