# Generated by Django 4.2.28 on 2026-03-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(db_index=True, help_text='Prescription ID this transaction relates to', max_length=64)),
                ('transaction_hash', models.CharField(blank=True, help_text='Ethereum transaction hash (0x...)', max_length=66, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('create', 'Prescription Created'), ('fill', 'Prescription Filled'), ('cancel', 'Prescription Cancelled'), ('verify', 'Prescription Verified')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('gas_used', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if transaction failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='Django user who triggered this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prescription_id'], name='blockchain__prescri_973538_idx'), models.Index(fields=['transaction_hash'], name='blockchain__transac_697a0b_idx'), models.Index(fields=['status'], name='blockchain__status_096a5b_idx')],
            },
        ),
    ]
